server:
  port: 8092

spring:
  datasource:
    username: root
    password: root
    # 116.62.178.244
    #url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    url: jdbc:mysql://116.62.178.244:3306/num?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 6000
      maximum-pool-size: 30
      minimum-idle: 10
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: rbkredis
    jedis:
      pool:
        max-active: 8
        max-wait: 1000ms
        max-idle: 8
        min-idle: 0
    timeout: 3000
  resources:
    static-locations: classpath:/static/,classpath:/templates/,classpath:/resources/


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.demo.dao: debug
